name: Release
on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    name: Upload to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: v16.13.0
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          dry-run: true
          ignore-scripts: false
          strategy: all
